### PR TITLE
[defunct] create argo_stage configuration, update argo_dev and argo_b configs

### PR DESCRIPTION
**Pull request by jmartin-sul**
@eefahy 

all 3 sets of configs should now match the current configuration on the argo develop branch (as of this commit).

per this afternoon's conversation:  my assumption is that while argo-stage-b will be the only argo-stage webserver at first, the eventual argo-stage-a will share the same config (the new argo 3.x schema).  hence, no argo_stage_b, just argo_stage.

by similar logic, i guess we'll eventually drop argo_b, when 3.x moves to prod, and argo-prod[-a|-b] uses the argo 3.x solr schema.  for now, of course, the solr config in argo should remain unchanged.

let me know if anything about this is out of line with the solr config update procedure...

### CODE REVIEW

**Comment by cbeer** [comment]
@jmartin-sul it looks like you dropped some important configuration in this update (the updateHandler, jmx, and `/get` request handler). I also don't know why you changed `LUCENE_4_10_4` to `4.9`, but I think we'd prefer the former unless there's a good reason?

**Comment by jmartin-sul** [comment]
well, on the advice of @atz, i was actually just using the versions of those files from argo's develop branch.  i'll defer to him since he did all of the solr schema and config work for argo, AFAIK.
https://github.com/sul-dlss/argo/blob/develop/solr_conf/conf/schema.xml
https://github.com/sul-dlss/argo/blob/develop/solr_conf/conf/solrconfig.xml

**Comment by cbeer** [comment]
Ok. In either case, these need to be fixed and the tests passing before this can be merged. Some of these requirements are important for it to run in a SolrCloud environment and are documented in the README:

https://github.com/sul-dlss/sul-solr-configs#required-configuration

**Comment by jmartin-sul** [comment]
superseded by pull #37

**Pull request closed without merging**
