### PR TITLE
attempt at unbreaking the document handler

### PR DESCRIPTION
**Pull request by jmartin-sul**
@sul-dlss/devops

### CODE REVIEW

**Comment by cbeer** [comment]
I'm happy to ship this, but what are you trying to do?

A request handler with a `/` prefix is accessible at:

`/solr/argo/document` or  `/solr/argo/select?qt=/document`

A request handler without the `/` is only accessible at

`/solr/argo/select?qt=document`

The latter style is now a discouraged (but still supported) practice, but I think Solr is trying to get people to migrate to the new style.

**Comment by jmartin-sul** [comment]
Right now, it looks like Argo is trying to use the "qt=document" style when rendering detail pages (and so it's getting a "400 Bad Request" back from Solr since that's an unknown handler).  I didn't know that style was deprecated, and went looking around Argo for something that configured that behavior explicitly (assuming Argo's behavior was out of date).  But I didn't end up finding anything to that effect, and a quick skim of a grep for "qt" in Blacklight's code, along with this documentation, both seem to indicate that Blacklight expects a "document" (instead of "/document") handler, unless BL is specifically configured otherwise:
https://github.com/projectblacklight/blacklight/wiki/Solr-Configuration#document-request-handler

The switch to "/document" was a result of my thinking that what was in argo_b's solrconfig.xml as of last week was what should be used for Argo's Solr Cloud deployments.  However, it appears that both the sul-solr-configs and the argo versions of the solrconfig.xml file were unfit as-is for deploying Argo's current develop branch to Solr Cloud (argo-prod-b was never used for its web UI, so it's not too surprising this wasn't noticed there, since Lynn discovered this problem when he went to do some testing on argo-dev).

Which is all a really long winded way of saying that I'd be in favor of shipping this change, assuming the above thinking is correct (apparently not a given for me with solr config stuff the last few days).  Seems reasonable to go with what Blacklight expects by default?

I'm also totally open to configuring Argo to use the new style behavior, if it is in fact reconfiguring BL unbeknownst to me, or if there are other benefits I'm not seeing in the new style even if it is the BL default.

**Comment by atz** [comment]
Glad to find there was a reason I initiated putting the slash in there.

**Comment by jmartin-sul** [comment]
convinced to switch to the new behavior.  closing this now that https://github.com/sul-dlss/argo/pull/46 is done.

**Pull request closed without merging**
